[package]
name = "twitch_bot"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0"
async-std = { version = "1.8.0", features = [ "attributes" ] }
futures = "0.3"
paw = "1.0"
lazy_static = "1.4.0"
twitch-irc = "3.0.1"
serde = { version = "1.0.136", features = ["derive"] }
sqlx = { version = "0.5.11", features = [ "runtime-tokio-rustls", "sqlite"] }
structopt = { version = "0.3", features = ["paw"] }
tokio = "1.17.0"
serde_json = "1.0.79"
dotenv = "0.15.0"